extends "res://scripts/tests/ToolPromotionTest.gd"

var promotion_sounds := 0

func _run() -> void:
	create_timer(100).timeout.connect(func(): push_error("Equipment feedback timed out"); quit(1))
	await _setup_crafting_fixture()
	var feedback := root.get_node("WorkFeedback")
	feedback.clear_transients()
	feedback.sound_started.connect(func(kind, _position, _variant):
		if kind == "promotion": promotion_sounds += 1)
	_expect(not worker.change_profession(CARPENTER) and promotion_sounds == 0, "failed promotion is silent")
	drops.restore_loose_item(KIT, Vector3(43.5,21,40.5), 0, 1)
	worker.change_profession(CARPENTER)
	await _equipment_stage("walking")
	_expect(promotion_sounds == 0, "request and reserved collection are silent")
	worker._equipment.cancel()
	_expect(promotion_sounds == 0, "cancellation is silent")
	worker.change_profession(CARPENTER)
	await _appointed()
	_expect(promotion_sounds == 1, "Carpenter completion plays one promotion cue")
	worker._process(.1)
	_expect(not worker.change_profession(CARPENTER) and promotion_sounds == 1, "repeat assignment and processing never replay cue")
	var factory = load("res://scripts/entities/DwarfFactory.gd").new()
	await _reload_worker(factory)
	_expect(promotion_sounds == 1, "restoring equipped role is silent")
	worker.change_profession(WORKER)
	_expect(promotion_sounds == 1, "returning to Worker is silent")
	feedback.clear_transients()
	clock_node.set_paused(true)
	worker.change_profession(MINER)
	_expect(promotion_sounds == 2, "immediate Miner promotion has feedback even while paused")
	worker.change_profession(WORKER)
	worker.change_profession(CARPENTER)
	worker._process(5)
	_expect(worker.profession == WORKER and promotion_sounds == 2, "paused queued promotion never plays early")
	clock_node.set_paused(false)
	feedback.clear_transients()
	await _appointed()
	_expect(promotion_sounds == 3, "resumed pickup plays only on completion")
	feedback.clear_transients()
	_expect(feedback.play_promotion(worker.position) and not feedback.play_promotion(worker.position), "notification voice bounds rapid repeats")
	feedback.clear_transients()
	_expect(feedback._promotion_player == null, "scene cleanup removes notification playback")
	await _review_views(factory)
	for failure in failures: push_error(failure)
	if failures.is_empty(): print("EQUIPMENT_FEEDBACK_OK: owned equipment, planned upgrades, embedded/standalone views, three resolutions, completion-only audio and no replay")
	quit(0 if failures.is_empty() else 1)

func _review_views(factory) -> void:
	director = load("res://scripts/entities/DwarfDirector.gd").new()
	director.name = "Dwarves"
	director.window_manager_path = NodePath("../Windows")
	scene.add_child(director)
	director._agents.append(worker)
	for i in range(4):
		var dwarf = factory.spawn(factory.generate(510+i, {}), 510+i)
		scene.add_child(dwarf)
		dwarf.set_process(false)
		dwarf.position = worker.position + Vector3(i*2+3,0,4)
		director._agents.append(dwarf)
	var explorer = load("res://scripts/ui/ObjectExplorerController.gd").new()
	explorer.window_manager_path = NodePath("../Windows")
	explorer.dwarf_director_path = NodePath("../Dwarves")
	scene.add_child(explorer)
	var inspection = load("res://scripts/components/DwarfInspection.gd")
	var stock_before: int = _count(KIT)
	for viewport in [Vector2i(1280,720), Vector2i(2560,1440), Vector2i(960,540)]:
		root.size = viewport
		manager.open("dwarves")
		director.inspect_dwarf(worker)
		await _frames(10)
		var detail = director._roster_panel._detail_panel
		_click(detail._tabs[2].get_global_rect().get_center())
		await _frames(4)
		_expect(detail._equipment_page.is_visible_in_tree(), "Equipment button opens embedded view " + str(viewport))
		_expect(detail._scroll.size.y >= 90, "embedded equipment keeps a usable scroll area " + str(viewport))
		_expect(detail._equipment_page._tool_name.text == "Crude Carpentry Kit", "equipment names actual owned item")
		_expect(detail._equipment_page._icon.texture != null, "equipment has existing kit thumbnail")
		_expect(detail._equipment_page._benefit.text.contains("No work-speed bonus"), "equipment states actual benefit")
		_expect(detail._equipment_page._upgrade_name.text == "Iron saw" and detail._equipment_page._upgrade_status.text.contains("Not craftable"), "future upgrade is named without pretending it exists")
		_expect(detail._equipment_page._upgrade_method.text.contains("Blacksmith"), "upgrade path explains maker and later assignment")
		_expect(director._roster_panel.window.get_global_rect().encloses(detail._change_profession.get_global_rect()), "profession and equipment navigation fit roster")
		await _equipment_capture("colony_%d" % viewport.x)
		detail._scroll.scroll_vertical = 2000
		await _frames(4)
		await _equipment_capture("colony_upgrade_%d" % viewport.x)
		manager.close("dwarves")
		director.inspect_dwarf(worker)
		await _frames(8)
		detail = explorer._dwarf_panel
		_click(detail._tabs[2].get_global_rect().get_center())
		await _frames(4)
		_expect(detail._equipment_page.is_visible_in_tree(), "Equipment opens standalone inspector " + str(viewport))
		_expect(explorer._window.get_global_rect().encloses(detail._change_profession.get_global_rect()), "standalone navigation stays inside inspector")
		_expect(explorer._window.size.x <= viewport.x-16, "inspector stays within viewport width")
		await _equipment_capture("inspector_%d" % viewport.x)
		detail._scroll.scroll_vertical = 2000
		await _frames(3)
		await _equipment_capture("inspector_upgrade_%d" % viewport.x)
		explorer.clear_selection()
	_expect(_count(KIT) == stock_before and worker.profession == CARPENTER, "equipment browsing never changes items or profession")
	worker.change_profession(MINER)
	var miner: Dictionary = inspection.equipment_details(worker)
	_expect(miner.name == "Default pickaxe" and miner.upgrade_name == "Iron pickaxe", "Miner distinguishes included pickaxe from future forged upgrade")
	worker.change_profession(WORKER)
	var generalist: Dictionary = inspection.equipment_details(worker)
	_expect(generalist.name == "Basic work tools" and generalist.upgrade_method.contains("Rudimentary"), "Worker shows accessible route to first specialist tools")

func _equipment_capture(label: String) -> void:
	if not "--capture" in OS.get_cmdline_user_args(): return
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png("res://tmp/equipment_ui_review/%s.png" % label)
